query kanjis (
    $searchInput: String
    $searchType: String
){
    kanjis (input: {
       searchInput: $searchInput
       searchType: $searchType 
    }) {
        writing
        on
        kun
        meaning
        imageUrl
    }
}