query kanjiSingle (
    $writing: String!
) {
    kanjiSingle (input : {
        writing: $writing
    }) {
        writing
        on
        kun
        meaning
        jlpt
        strokes
        imageUrl
        usageFirst {
            writing
            translation
            hiragana
            romaji
        }
        usageLast {
            writing
            translation
            hiragana
            romaji
        }
    }
}