query wordSingle (
    $writing: String!
) {
    wordSingle (input : {
        writing: $writing
    }) {
        writing
        translation
        hiragana
        romaji
        imageUrl
        usage {
            question
            answer
        }
    }
}