query words (
    $searchInput: String
    $searchType: String
){
    words (input: {
       searchInput: $searchInput
       searchType: $searchType 
    }) {
        writing
        translation
        hiragana
        romaji
    }
}