query wordSingle (
    $writing: String!
) {
    wordSingle (input : {
        writing: $writing
    }) {
        writing
        translation
        hiragana
        romaji
        imageUrl
        kanji {
            writing
        }
        usage {
            question
            answer
        }
        usageMeaning {
            question
            answer
        }
        usageDifference {
            question
            answer
        }
        usageWatsay {
            question
            answer
        }
        usageOther {
            question
            answer
        }
    }
}