variables:
  TEST: "shintokaido@88.212.253.151"

stages:
  - deploy_test
deploy_test:
  stage: deploy_test
  only:
    - dev
  script:
    - yarn
    - yarn build:sandbox
    - ssh $TEST 'cd /home/shintokaido/jiten/ && yarn fork:sandbox'
  environment:
    name: deploy_test
  